name: CI Pipeline

on:
  push:
    branches:
      - main
      - tasks/USR-0
      - test/ci-check

  pull_request:
    branches:
      - main

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build and test
        run: mvn verify

      - name: Run Sonar analysis
        run: mvn sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker
        run: docker build -t user-service-app .